# Ubuntu 14.04 Trusty support
sudo: false
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - uname -a
  - clang++ --version 2>&1 | grep clang
  - g++ --version 2>&1 | grep g++

script:
  - ls -al
  - make

notifications:
  email:
    recipients:
      - michael142536@gmail.com 
      - alanwanga@yahoo.com.tw
    on_success: change
    on_failure: always
