sudo: false
language: cpp
compiler:
  - gcc
  - clang

  addons:
    apt:
      sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
      packages:
        - gcc-4.8
        - g++-4.8
        - clang-3.7

before_script:
    - uname -a
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++

script:
    - ls -al
    - make
